camera:
  frame_id: camera_link
  width: 640
  height: 480
  distortion_model: plumb_bob

intrinsics:
  fx: 670.14085
  fy: 720.39775
  cx: 328.21091
  cy: 240.90649
  k1: 0.043153
  k2: 0.219945
  p1: 0.000000
  p2: 0.000000
  k3: 0.000000

extrinsics:
  pitch_deg: 14.9511
  yaw_deg: 0.0000
  roll_deg: 0.0000
  height_m: 0.2683

bev:
  x_min: 0.0
  x_max: 2.5
  y_min: -0.9
  y_max: 0.9
  output_width: 640
  output_height: 480
  
metric:
  meters_per_pixel_x: 0.003994
  meters_per_pixel_y: 0.002357

  origin_u: 320.0
  origin_v: 410.0

  bev_origin_to_camera_x_m: 0.38
  bev_origin_to_camera_y_m: 0.0

  camera_to_base_x_m: -0.23
  camera_to_base_y_m: 0.0

viz_metric:
  x_min: 0.0
  x_max: 1.8
  y_min: -0.7
  y_max: 0.7
