camera:
  frame_id: camera_link
  width: 640
  height: 480
  distortion_model: plumb_bob

intrinsics:
  # [정밀 데이터] 0.3508px 오차율 기반 원본 값
  fx: 672.94664
  fy: 678.60968
  cx: 342.41670
  cy: 251.36037
  k1: -0.442943
  k2: 0.330594
  p1: 0.000000
  p2: 0.000000
  k3: 0.000000

extrinsics:
  pitch_deg: 14.7260
  yaw_deg: 0.0000    # 측정값 없을 시 0
  roll_deg: 0.0000   # 측정값 없을 시 0
  height_m: 0.274

bev:
  x_min: 0.12
  x_max: 2.0
  y_min: -0.85
  y_max: 0.85
  output_width: 480
  output_height: 640
  #내부 파라미터 오차율 0.3508픽셀 외부파라미터는 그냥 높이만 직접 수정
  
metric:
  meters_per_pixel_x: 0.003151
  meters_per_pixel_y: 0.003151

  origin_u: 320.0
  origin_v: 479.0

  bev_origin_to_camera_x_m: 0.43
  bev_origin_to_camera_y_m: 0.0

  camera_to_base_x_m: -0.23
  camera_to_base_y_m: 0.0

viz_metric:
  x_min: 0.0
  x_max: 1.8
  y_min: -0.7
  y_max: 0.7
